// TextClockHarmonyApp.ts - HarmonyOS TextClock Application
// Using 131 Adapters to convert Android TextClock to HarmonyOS
// Auto-generated by OpenClaw Agent

import { BundleAdapter } from './16.1.2-ADAPTER-DEVELOPMENT/16.1.20-BUNDLE-ADAPTER/coding';
import { AppCompatActivityAdapter, ActivityState } from './16.1.2-ADAPTER-DEVELOPMENT/16.1.20-APPCOMPAT-ADAPTER/coding';
import { ButtonAdapter } from './16.1.2-ADAPTER-DEVELOPMENT/16.1.21-BUTTON-ADAPTER/coding';
import { TextViewAdapter } from './16.1.2-ADAPTER-DEVELOPMENT/16.1.22-TEXTVIEW-ADAPTER/coding';
import { TextClockAdapter } from './16.1.2-ADAPTER-DEVELOPMENT/16.1.22-TEXTCLOCK-ADAPTER/coding';
import { TimeZoneAdapter } from './16.1.2-ADAPTER-DEVELOPMENT/16.1.22-TIMEZONE-ADAPTER/coding';
import { EventAdapter } from './16.1.2-ADAPTER-DEVELOPMENT/16.1.23-ONCLICK-ADAPTER/coding';

/**
 * MainActivity - HarmonyOS version of Android TextClock
 * 
 * Original Android: com.w.homework2.MainActivity
 * Converted to HarmonyOS using 16.1-Adapters
 */
class MainActivity extends AppCompatActivityAdapter {
  // Android: Button TimeZoneButton;
  private timeZoneButton: ButtonAdapter;
  
  // Android: TextView TimeZoneTextview;
  private timeZoneTextView: TextViewAdapter;
  
  // Android: TextClock (in layout)
  private textClock: TextClockAdapter;
  
  // Event handling
  private eventAdapter: EventAdapter;
  
  constructor() {
    super();
    this.timeZoneButton = new ButtonAdapter('Get Time Zone');
    this.timeZoneTextView = new TextViewAdapter('TimeZone');
    this.textClock = new TextClockAdapter({
      format12Hour: 'hh:mm:ss',
      textSize: 35,
      textColor: '#FF4081'
    });
    this.eventAdapter = new EventAdapter();
  }
  
  /**
   * Android: onCreate(Bundle savedInstanceState)
   */
  protected onCreate(savedInstanceState: BundleAdapter): void {
    console.log('[MainActivity] onCreate called');
    
    // Android: setContentView(R.layout.activity_main);
    // HarmonyOS: Layout is built programmatically using Adapters
    
    // Android: TimeZoneButton = (Button) findViewById(R.id.timeZoneButton);
    // Already initialized in constructor
    
    // Android: TimeZoneTextview = findViewById(R.id.timeZoneShow);
    // Already initialized in constructor
    
    // Android: TimeZoneButton.setOnClickListener(...)
    this.setupClickListener();
    
    console.log('[MainActivity] Views initialized:');
    console.log('  - TextClock: running=' + this.textClock.isClockRunning());
    console.log('  - Button: text="' + this.timeZoneButton.getText() + '"');
    console.log('  - TextView: text="' + this.timeZoneTextView.getText() + '"');
  }
  
  /**
   * Setup click listener (converted from Android anonymous class)
   */
  private setupClickListener(): void {
    // Register click handler
    this.eventAdapter.setOnClickListener('timeZoneButton', () => {
      this.onTimeZoneButtonClick();
    });
    
    // Connect to button
    this.timeZoneButton.setOnClickListener(() => {
      this.eventAdapter.triggerClick('timeZoneButton');
    });
  }
  
  /**
   * Handle button click
   * Android: onClick(View view) { ... }
   */
  private onTimeZoneButtonClick(): void {
    console.log('[MainActivity] Button clicked');
    
    // Android: TimeZone tz = TimeZone.getDefault();
    const tz = TimeZoneAdapter.getDefault();
    
    // Android: TimeZoneTextview.setText("Time Zone : " + tz.getDisplayName(...) + ...);
    const displayText = `Time Zone: ${tz.getDisplayName(false, true)} | ID: ${tz.getID()}`;
    this.timeZoneTextView.setText(displayText);
    
    console.log('[MainActivity] Updated: ' + displayText);
  }
  
  /**
   * Android: onPause()
   */
  protected onPause(): void {
    console.log('[MainActivity] onPause - stopping clock');
    this.textClock.stopClock();
  }
  
  /**
   * Android: onResume()
   */
  protected onResume(): void {
    console.log('[MainActivity] onResume - restarting clock');
    this.textClock.restartClock();
  }
  
  /**
   * Android: onDestroy()
   */
  protected onDestroy(): void {
    console.log('[MainActivity] onDestroy - cleaning up');
    this.textClock.destroy();
  }
  
  /**
   * Get current UI state for display
   */
  getUIState(): any {
    return {
      clock: {
        running: this.textClock.isClockRunning(),
        currentTime: this.textClock.getCurrentTime(),
        timeZone: this.textClock.getTimeZone()
      },
      button: {
        text: this.timeZoneButton.getText(),
        enabled: this.timeZoneButton.isEnabled()
      },
      textView: {
        text: this.textZoneTextView.getText()
      },
      activityState: this.getState()
    };
  }
}

/**
 * Demo runner - Simulates app lifecycle
 */
export function runTextClockDemo(): void {
  console.log('\n========================================');
  console.log('TextClock HarmonyOS Demo');
  console.log('Using 16.1-Adapters');
  console.log('========================================\n');
  
  // Create activity
  const activity = new MainActivity();
  
  // Simulate app start
  console.log('>>> App Starting...');
  activity.onPageShow();
  
  // Show initial state
  console.log('\nInitial State:');
  console.log(JSON.stringify(activity.getUIState(), null, 2));
  
  // Wait a moment then click button
  setTimeout(() => {
    console.log('\n>>> User clicks button...');
    activity.timeZoneButton.performClick();
    
    // Show updated state
    console.log('\nUpdated State:');
    console.log(JSON.stringify(activity.getUIState(), null, 2));
    
    // Simulate app background
    setTimeout(() => {
      console.log('\n>>> App going to background...');
      activity.onPageHide();
      
      console.log('\nPaused State:');
      console.log(JSON.stringify(activity.getUIState(), null, 2));
      
      // Simulate app resume
      setTimeout(() => {
        console.log('\n>>> App resuming...');
        activity.onPageShow();
        
        console.log('\nResumed State:');
        console.log(JSON.stringify(activity.getUIState(), null, 2));
        
        // Close app
        setTimeout(() => {
          console.log('\n>>> App closing...');
          activity.onPageDestroy();
          
          console.log('\n========================================');
          console.log('Demo Complete!');
          console.log('========================================\n');
        }, 1000);
      }, 1000);
    }, 2000);
  }, 2000);
}

// Run demo if executed directly
if (require.main === module) {
  runTextClockDemo();
}

// Export for module usage
export { MainActivity };
export default MainActivity;
