// BundleAdapter.ts - Android Bundle to HarmonyOS wantParams
// Part of 16.1-AndroidToHarmonyOSDemo Project
// Auto-generated by OpenClaw Agent

/**
 * Adapter for Android Bundle → HarmonyOS wantParams
 * 
 * Android: android.os.Bundle
 * HarmonyOS: wantParams (Record<string, any>)
 * 
 * Complexity: ⭐ Low
 * Estimated Time: 4 hours
 */

export class BundleAdapter {
  private params: Map<string, any> = new Map();

  /**
   * Create empty Bundle
   */
  constructor();
  
  /**
   * Create Bundle from existing wantParams
   */
  constructor(wantParams: Record<string, any>);
  
  constructor(wantParams?: Record<string, any>) {
    if (wantParams) {
      Object.entries(wantParams).forEach(([key, value]) => {
        this.params.set(key, value);
      });
    }
  }

  /**
   * Static factory method to create from wantParams
   * Maps to: Bundle.fromWantParams()
   */
  static fromWantParams(params: Record<string, any>): BundleAdapter {
    return new BundleAdapter(params);
  }

  /**
   * Put a value into the Bundle
   * Maps to: bundle.putString(), bundle.putInt(), etc.
   */
  put(key: string, value: any): void {
    this.params.set(key, value);
  }

  /**
   * Get a value from the Bundle
   * Maps to: bundle.get(), bundle.getString(), etc.
   */
  get(key: string): any | undefined {
    return this.params.get(key);
  }

  /**
   * Get string value
   */
  getString(key: string): string | undefined {
    const value = this.params.get(key);
    return value !== undefined ? String(value) : undefined;
  }

  /**
   * Get string value with default
   */
  getString(key: string, defaultValue: string): string {
    const value = this.params.get(key);
    return value !== undefined ? String(value) : defaultValue;
  }

  /**
   * Get integer value
   */
  getInt(key: string): number | undefined {
    const value = this.params.get(key);
    return value !== undefined ? parseInt(value, 10) : undefined;
  }

  /**
   * Get integer value with default
   */
  getInt(key: string, defaultValue: number): number {
    const value = this.params.get(key);
    return value !== undefined ? parseInt(value, 10) : defaultValue;
  }

  /**
   * Get boolean value
   */
  getBoolean(key: string): boolean | undefined {
    const value = this.params.get(key);
    return value !== undefined ? Boolean(value) : undefined;
  }

  /**
   * Get boolean value with default
   */
  getBoolean(key: string, defaultValue: boolean): boolean {
    const value = this.params.get(key);
    return value !== undefined ? Boolean(value) : defaultValue;
  }

  /**
   * Check if key exists
   */
  containsKey(key: string): boolean {
    return this.params.has(key);
  }

  /**
   * Remove a key
   */
  remove(key: string): void {
    this.params.delete(key);
  }

  /**
   * Clear all data
   */
  clear(): void {
    this.params.clear();
  }

  /**
   * Get all keys
   */
  keySet(): string[] {
    return Array.from(this.params.keys());
  }

  /**
   * Check if empty
   */
  isEmpty(): boolean {
    return this.params.size === 0;
  }

  /**
   * Get size
   */
  size(): number {
    return this.params.size;
  }

  /**
   * Convert to wantParams for HarmonyOS
   */
  toWantParams(): Record<string, any> {
    const result: Record<string, any> = {};
    this.params.forEach((value, key) => {
      result[key] = value;
    });
    return result;
  }

  /**
   * Clone the Bundle
   */
  clone(): BundleAdapter {
    const cloned = new BundleAdapter();
    this.params.forEach((value, key) => {
      cloned.put(key, value);
    });
    return cloned;
  }
}

// Usage Example:
/*
// Android way:
Bundle bundle = new Bundle();
bundle.putString("username", "John");
bundle.putInt("age", 25);
String name = bundle.getString("username");

// HarmonyOS way with Adapter:
const bundle = new BundleAdapter();
bundle.put("username", "John");
bundle.put("age", 25);
const name = bundle.getString("username");

// Convert to wantParams:
const wantParams = bundle.toWantParams();
// wantParams = { username: "John", age: 25 }
*/
