// coding.ts - EventAdapter Implementation
// Part of 16.1-AndroidToHarmonyOSDemo Project
// Auto-generated by OpenClaw Agent

/**
 * Adapter for Android OnClickListener → HarmonyOS onClick
 * 
 * Android: View.OnClickListener
 * HarmonyOS: onClick callback / Gesture
 * 
 * Complexity: ⭐ Low
 * Estimated Time: 4 hours
 * Status: ✅ Implemented
 */

/**
 * Type definition for click listener callback
 */
export type OnClickListener = (view?: any) => void;

/**
 * EventAdapter - Manages click event listeners
 * 
 * Provides Android-compatible event handling for HarmonyOS
 */
export class EventAdapter {
  private listeners: Map<string, OnClickListener[]> = new Map();
  private viewListeners: WeakMap<any, OnClickListener> = new WeakMap();

  /**
   * Register a click listener for a view by ID
   * Maps to: view.setOnClickListener(listener)
   */
  setOnClickListener(viewId: string, listener: OnClickListener): void {
    if (!this.listeners.has(viewId)) {
      this.listeners.set(viewId, []);
    }
    this.listeners.get(viewId)!.push(listener);
  }

  /**
   * Register a click listener directly on a view object
   */
  setOnClickListenerForView(view: any, listener: OnClickListener): void {
    this.viewListeners.set(view, listener);
    
    // Attach HarmonyOS onClick if view supports it
    if (view && typeof view.onClick === 'function') {
      view.onClick(() => {
        listener(view);
      });
    }
  }

  /**
   * Trigger click event for a view
   */
  triggerClick(viewId: string, view?: any): void {
    const listeners = this.listeners.get(viewId) || [];
    listeners.forEach(listener => listener(view));
  }

  /**
   * Remove a specific listener
   */
  removeOnClickListener(viewId: string, listener: OnClickListener): void {
    const listeners = this.listeners.get(viewId) || [];
    const index = listeners.indexOf(listener);
    if (index > -1) {
      listeners.splice(index, 1);
    }
  }

  /**
   * Remove all listeners for a view
   */
  removeAllListeners(viewId: string): void {
    this.listeners.delete(viewId);
  }

  /**
   * Check if view has listeners
   */
  hasListeners(viewId: string): boolean {
    const listeners = this.listeners.get(viewId);
    return listeners !== undefined && listeners.length > 0;
  }

  /**
   * Get listener count for a view
   */
  getListenerCount(viewId: string): number {
    const listeners = this.listeners.get(viewId);
    return listeners ? listeners.length : 0;
  }

  /**
   * Clear all listeners
   */
  clear(): void {
    this.listeners.clear();
  }
}

/**
 * Simplified click listener for direct use
 * 
 * Usage:
 * button.onClick(onClickAdapter((view) => {
 *   console.log('Button clicked!');
 * }));
 */
export function onClickAdapter(listener: OnClickListener): () => void {
  return () => {
    listener();
  };
}

/**
 * View.OnClickListener compatible interface
 * 
 * For code that expects Android-style interface
 */
export interface View {
  onClick(listener: OnClickListener): void;
}

// Export for module usage
export default EventAdapter;
