#!/bin/bash
# 16.1.121 - Code Structure Analysis
# Auto-generated by OpenClaw Agent
# Date: 2026-03-09

set -e

PROJECT_DIR="/mnt/d/ObsidianVault/10-Projects/16-DigitalEmployee/16.1-AndroidToHarmonyOSDemo"
ANALYSIS_DIR="$PROJECT_DIR/16.1.1-ANDROID-ANALYSIS/16.1.12-CODE-ANALYSIS"
PROJECT_PATH="$PROJECT_DIR/16.1.1-ANDROID-ANALYSIS/16.1.10-POC-DOWNLOAD/TextClock"
REPORT_FILE="$ANALYSIS_DIR/code-structure.md"

echo "=========================================="
echo "16.1.121 - Code Structure Analysis"
echo "=========================================="
echo ""

mkdir -p "$ANALYSIS_DIR"
cd "$PROJECT_PATH"
START_TIME=$(date +%s)

echo "[1/5] Analyzing project structure..."

# Generate directory tree
echo "Generating file tree..."
tree -I '.git|.idea|build' -L 4 > /tmp/project_tree.txt 2>/dev/null || find . -type f -not -path "./.git/*" -not -path "./.idea/*" -not -path "./build/*" | head -50 > /tmp/project_tree.txt

echo "  Total directories: $(find . -type d -not -path "./.git/*" -not -path "./.idea/*" | wc -l)"
echo "  Total files: $(find . -type f -not -path "./.git/*" -not -path "./.idea/*" | wc -l)"

echo ""
echo "[2/5] Analyzing Java source code..."

JAVA_FILES=$(find . -name "*.java" -type f)
JAVA_FILE_COUNT=$(echo "$JAVA_FILES" | wc -l)
JAVA_TOTAL_LINES=$(find . -name "*.java" -type f -exec wc -l {} + 2>/dev/null | tail -1 | awk '{print $1}')

echo "  Java files: $JAVA_FILE_COUNT"
echo "  Total lines: $JAVA_TOTAL_LINES"

# Analyze MainActivity in detail
MAIN_ACTIVITY="app/src/main/java/com/w/homework2/MainActivity.java"
if [ -f "$MAIN_ACTIVITY" ]; then
    echo ""
    echo "  MainActivity.java Analysis:"
    echo "  - Lines: $(wc -l < "$MAIN_ACTIVITY")"
    echo "  - Package: $(grep "^package" "$MAIN_ACTIVITY" | sed 's/package //;s/;//')"
    echo "  - Imports: $(grep -c "^import" "$MAIN_ACTIVITY")"
    echo "  - Methods: $(grep -c "void\|String\|int\|boolean\|TimeZone" "$MAIN_ACTIVITY")"
    
    # Extract class hierarchy
    CLASS_LINE=$(grep "public class" "$MAIN_ACTIVITY")
    echo "  - Class: $CLASS_LINE"
fi

echo ""
echo "[3/5] Analyzing XML layouts..."

XML_FILES=$(find . -name "*.xml" -type f -not -path "./.idea/*")
XML_FILE_COUNT=$(echo "$XML_FILES" | wc -l)
XML_TOTAL_LINES=$(find . -name "*.xml" -type f -not -path "./.idea/*" -exec wc -l {} + 2>/dev/null | tail -1 | awk '{print $1}')

echo "  XML files: $XML_FILE_COUNT"
echo "  Total lines: $XML_TOTAL_LINES"

# Analyze main layout
LAYOUT_FILE="app/src/main/res/layout/activity_main.xml"
if [ -f "$LAYOUT_FILE" ]; then
    echo ""
    echo "  activity_main.xml Analysis:"
    echo "  - Lines: $(wc -l < "$LAYOUT_FILE")"
    echo "  - Root element: $(grep -oP '(?<=<)[^/\s>]+' "$LAYOUT_FILE" | head -1)"
    
    # Count view types
    echo "  - View components:"
    grep -oE "<(Button|TextView|TextClock|ConstraintLayout|EditText|ImageView)" "$LAYOUT_FILE" | sort | uniq -c | sed 's/^/    /'
fi

echo ""
echo "[4/5] Extracting API usage patterns..."

# Extract all Android APIs used
echo "  Android APIs found in MainActivity.java:"
grep -E "import android|import androidx" "$MAIN_ACTIVITY" 2>/dev/null | sed 's/import //;s/;//' | sed 's/^/    /' || echo "    None found"

echo ""
echo "  Method calls in MainActivity.java:"
grep -oE "\.(setContentView|findViewById|setOnClickListener|setText|getDefault|getDisplayName|getID)" "$MAIN_ACTIVITY" 2>/dev/null | sort | uniq -c | sed 's/^/    /' || echo "    None found"

echo ""
echo "[5/5] Generating class diagram info..."

# Create class relationship info
cat > "$REPORT_FILE" << 'EOF'
---
tags:
  - project/dev
  - android
  - code-analysis
date: $(date +%Y-%m-%d)
status: completed
---

# Code Structure Analysis - TextClock

## Project Overview

| Metric | Value |
|--------|-------|
| **Project** | TextClock (Homework2) |
| **Package** | com.w.homework2 |
| **Analysis Date** | $(date '+%Y-%m-%d %H:%M:%S') |
| **Java Files** | $JAVA_FILE_COUNT |
| **Java Lines** | $JAVA_TOTAL_LINES |
| **XML Files** | $XML_FILE_COUNT |
| **XML Lines** | $XML_TOTAL_LINES |

## Directory Structure

\`\`\`
EOF

cat /tmp/project_tree.txt >> "$REPORT_FILE"

cat >> "$REPORT_FILE" << EOF
\`\`\`

## Class Analysis

### MainActivity

\`\`\`java
$(cat "$MAIN_ACTIVITY" 2>/dev/null || echo "// File not found")
\`\`\`

### Class Hierarchy

\`\`\`
AppCompatActivity (androidx)
    └── MainActivity (com.w.homework2)
            ├── TimeZoneButton : Button
            ├── TimeZoneTextview : TextView
            └── onCreate(Bundle)
                └── OnClickListener
                    └── onClick(View)
                        └── TimeZone.getDefault()
\`\`\`

## Layout Analysis

### activity_main.xml

\`\`\`xml
$(cat "$LAYOUT_FILE" 2>/dev/null || echo "<!-- File not found -->")
\`\`\`

### View Hierarchy

\`\`\`
ConstraintLayout (root)
├── TextClock (idTextClock)
│   └── format12Hour: "hh:mm:ss"
├── Button (timeZoneButton)
│   └── text: "Get Time Zone"
└── TextView (timeZoneShow)
    └── text: "TimeZone"
\`\`\`

## API Usage Summary

### Android APIs Used

| # | API | Purpose | Location |
|---|-----|---------|----------|
| 1 | AppCompatActivity | Base activity class | Class declaration |
| 2 | Bundle | State management | onCreate parameter |
| 3 | setContentView | Layout loading | onCreate |
| 4 | findViewById | View lookup | onCreate |
| 5 | Button | UI component | Field + Layout |
| 6 | TextView | UI component | Field + Layout |
| 7 | TextClock | Time display | Layout |
| 8 | ConstraintLayout | Layout container | Layout root |
| 9 | OnClickListener | Event handling | Anonymous class |
| 10 | TimeZone | Time zone data | onClick |

### Method Call Graph

\`\`\`
onCreate(Bundle)
├── setContentView(R.layout.activity_main)
├── findViewById(R.id.timeZoneButton) → TimeZoneButton
├── findViewById(R.id.timeZoneShow) → TimeZoneTextview
└── TimeZoneButton.setOnClickListener(OnClickListener)
    └── onClick(View)
        ├── TimeZone.getDefault()
        ├── TimeZone.getDisplayName()
        ├── TimeZone.getID()
        └── TimeZoneTextview.setText(String)
\`\`\`

## Dependencies

### Gradle Dependencies

\`\`\`
$(grep -A5 "dependencies" build.gradle 2>/dev/null || echo "// Not found")
\`\`\`

## Complexity Metrics

| Metric | Value |
|--------|-------|
| Cyclomatic Complexity | Low (simple onClick) |
| Method Count | 2 (onCreate, onClick) |
| Class Count | 1 (MainActivity) |
| View Count | 3 (TextClock, Button, TextView) |

## Next Steps

1. ✅ Code structure analysis (16.1.121)
2. ⏳ API extraction (16.1.131)
3. ⏳ Generate analysis report (16.1.141)

---

**Generated**: $(date '+%Y-%m-%d %H:%M:%S')  
**Script**: 16.1.121-code_structure_analysis.sh
EOF

END_TIME=$(date +%s)
DURATION=$((END_TIME - START_TIME))

echo ""
echo "=========================================="
echo "Code Analysis Complete!"
echo "=========================================="
echo "Duration: $DURATION seconds"
echo "Report: $REPORT_FILE"

exit 0
