#!/bin/bash
# 16.1.102 - Verify TextClock Project Integrity
# Auto-generated by OpenClaw Agent
# Date: 2026-03-09

set -e

PROJECT_DIR="/mnt/d/ObsidianVault/10-Projects/16-DigitalEmployee/16.1-AndroidToHarmonyOSDemo"
DOWNLOAD_DIR="$PROJECT_DIR/16.1.1-ANDROID-ANALYSIS/16.1.10-POC-DOWNLOAD"
PROJECT_NAME="TextClock"
PROJECT_PATH="$DOWNLOAD_DIR/$PROJECT_NAME"
REPORT_FILE="$DOWNLOAD_DIR/integrity-check.md"

echo "=========================================="
echo "16.1.102 - Verify Project Integrity"
echo "=========================================="
echo ""

if [ ! -d "$PROJECT_PATH" ]; then
    echo "✗ Project not found at $PROJECT_PATH"
    echo "Please run 16.1.101 first."
    exit 1
fi

cd "$PROJECT_PATH"
START_TIME=$(date +%s)

echo "[1/6] Checking project structure..."

REQUIRED_DIRS=(
    "app/src/main/java"
    "app/src/main/res/layout"
    "app/src/main/res/values"
    "gradle"
)

for dir in "${REQUIRED_DIRS[@]}"; do
    if [ -d "$dir" ]; then
        echo "  ✓ $dir/"
    else
        echo "  ✗ $dir/ (missing)"
    fi
done

echo ""
echo "[2/6] Verifying core files..."

REQUIRED_FILES=(
    "app/src/main/java/com/w/homework2/MainActivity.java"
    "app/src/main/res/layout/activity_main.xml"
    "app/src/main/AndroidManifest.xml"
    "build.gradle"
    "settings.gradle"
    "gradlew"
    "gradle/wrapper/gradle-wrapper.properties"
)

ALL_PRESENT=true
for file in "${REQUIRED_FILES[@]}"; do
    if [ -f "$file" ]; then
        SIZE=$(ls -lh "$file" | awk '{print $5}')
        echo "  ✓ $file ($SIZE)"
    else
        echo "  ✗ $file (missing)"
        ALL_PRESENT=false
    fi
done

echo ""
echo "[3/6] Analyzing MainActivity.java..."

MAIN_ACTIVITY="app/src/main/java/com/w/homework2/MainActivity.java"
if [ -f "$MAIN_ACTIVITY" ]; then
    # Extract key information
    PACKAGE=$(grep "^package" "$MAIN_ACTIVITY" | head -1)
    CLASS_NAME=$(grep "public class" "$MAIN_ACTIVITY" | head -1)
    EXTENDS=$(grep "extends" "$MAIN_ACTIVITY" | head -1)
    
    echo "  Package: $PACKAGE"
    echo "  Class: $CLASS_NAME"
    echo "  Extends: $EXTENDS"
    
    # Count methods
    METHOD_COUNT=$(grep -c "void\|String\|int\|boolean" "$MAIN_ACTIVITY" || echo "0")
    echo "  Estimated methods: $METHOD_COUNT"
fi

echo ""
echo "[4/6] Analyzing layout file..."

LAYOUT_FILE="app/src/main/res/layout/activity_main.xml"
if [ -f "$LAYOUT_FILE" ]; then
    # Count views
    VIEW_COUNT=$(grep -oE "<(Button|TextView|TextClock|ConstraintLayout)" "$LAYOUT_FILE" | wc -l)
    echo "  Views found: $VIEW_COUNT"
    
    # List view types
    echo "  View types:"
    grep -oE "<(Button|TextView|TextClock|ConstraintLayout)" "$LAYOUT_FILE" | sort | uniq -c | sed 's/^/    /'
fi

echo ""
echo "[5/6] Checking build configuration..."

if [ -f "build.gradle" ]; then
    echo "  Build file present"
    
    # Extract SDK versions
    COMPILE_SDK=$(grep "compileSdk" build.gradle | head -1 | sed 's/.*compileSdk //')
    MIN_SDK=$(grep "minSdk" build.gradle | head -1 | sed 's/.*minSdk //')
    TARGET_SDK=$(grep "targetSdk" build.gradle | head -1 | sed 's/.*targetSdk //')
    
    echo "  Compile SDK: $COMPILE_SDK"
    echo "  Min SDK: $MIN_SDK"
    echo "  Target SDK: $TARGET_SDK"
fi

if [ -f "gradle/wrapper/gradle-wrapper.properties" ]; then
    GRADLE_VERSION=$(grep "distributionUrl" gradle/wrapper/gradle-wrapper.properties | sed 's/.*gradle-//' | sed 's/-bin.*//')
    echo "  Gradle version: $GRADLE_VERSION"
fi

echo ""
echo "[6/6] Running basic syntax checks..."

# Check Java syntax
JAVA_ERRORS=0
for java_file in $(find . -name "*.java" -type f); do
    # Basic check for unmatched braces
    OPEN_BRACES=$(grep -o '{' "$java_file" | wc -l)
    CLOSE_BRACES=$(grep -o '}' "$java_file" | wc -l)
    if [ "$OPEN_BRACES" -ne "$CLOSE_BRACES" ]; then
        echo "  ⚠ $java_file - Brace mismatch"
        JAVA_ERRORS=$((JAVA_ERRORS + 1))
    fi
done

if [ $JAVA_ERRORS -eq 0 ]; then
    echo "  ✓ All Java files passed basic syntax check"
else
    echo "  ⚠ $JAVA_ERRORS files have potential issues"
fi

# Check XML well-formedness
XML_ERRORS=0
for xml_file in $(find . -name "*.xml" -type f); do
    if ! xmllint --noout "$xml_file" 2>/dev/null; then
        echo "  ⚠ $xml_file - XML parsing error"
        XML_ERRORS=$((XML_ERRORS + 1))
    fi
done

if [ $XML_ERRORS -eq 0 ]; then
    echo "  ✓ All XML files are well-formed"
else
    echo "  ⚠ $XML_ERRORS XML files have issues"
fi

END_TIME=$(date +%s)
DURATION=$((END_TIME - START_TIME))

echo ""
echo "=========================================="
echo "Generating report..."
echo "=========================================="

cat > "$REPORT_FILE" << EOF
---
tags:
  - project/dev
  - android
  - integrity-check
date: $(date +%Y-%m-%d)
status: $(if [ "$ALL_PRESENT" = true ]; then echo "verified"; else echo "issues-found"; fi)
---

# Integrity Check Report - TextClock PoC

## Summary

| Metric | Value |
|--------|-------|
| **Project Path** | $PROJECT_PATH |
| **Check Date** | $(date '+%Y-%m-%d %H:%M:%S') |
| **Duration** | $DURATION seconds |
| **Status** | $(if [ "$ALL_PRESENT" = true ]; then echo "✅ All core files present"; else echo "⚠️ Some files missing"; fi) |

## Core Files Status

| File | Status | Size |
|------|--------|------|
EOF

for file in "${REQUIRED_FILES[@]}"; do
    if [ -f "$file" ]; then
        SIZE=$(ls -lh "$file" 2>/dev/null | awk '{print $5}')
        echo "| $file | ✅ | $SIZE |" >> "$REPORT_FILE"
    else
        echo "| $file | ❌ | - |" >> "$REPORT_FILE"
    fi
done

cat >> "$REPORT_FILE" << EOF

## Code Analysis

### MainActivity.java
- **Package**: $(grep "^package" "$MAIN_ACTIVITY" 2>/dev/null | head -1 || echo "N/A")
- **Class**: $(grep "public class" "$MAIN_ACTIVITY" 2>/dev/null | head -1 || echo "N/A")
- **Line Count**: $(wc -l < "$MAIN_ACTIVITY" 2>/dev/null || echo "0")

### Layout Analysis
- **Views**: $VIEW_COUNT
- **Layout File**: activity_main.xml

### Build Configuration
- **Compile SDK**: $COMPILE_SDK
- **Min SDK**: $MIN_SDK
- **Target SDK**: $TARGET_SDK
- **Gradle**: $GRADLE_VERSION

## Validation Results

| Check | Status |
|-------|--------|
| Project Structure | $(if [ -d "app/src/main/java" ]; then echo "✅"; else echo "❌"; fi) |
| Core Files | $(if [ "$ALL_PRESENT" = true ]; then echo "✅"; else echo "⚠️"; fi) |
| Java Syntax | $(if [ $JAVA_ERRORS -eq 0 ]; then echo "✅"; else echo "⚠️"; fi) |
| XML Well-formed | $(if [ $XML_ERRORS -eq 0 ]; then echo "✅"; else echo "⚠️"; fi) |

## Issues Found

- Java syntax issues: $JAVA_ERRORS
- XML issues: $XML_ERRORS

## Next Steps

1. ✅ Download (16.1.101)
2. ✅ Verify integrity (16.1.102)
3. ⏳ Configure Android SDK (16.1.111)
4. ⏳ Build APK (16.1.113)

---

**Generated**: $(date '+%Y-%m-%d %H:%M:%S')  
**Script**: 16.1.102-verify_integrity.sh
EOF

echo "✓ Report generated: $REPORT_FILE"

echo ""
echo "=========================================="
echo "Integrity Check Complete!"
echo "=========================================="
echo "Duration: $DURATION seconds"
echo "Status: $(if [ "$ALL_PRESENT" = true ]; then echo "✅ Verified"; else echo "⚠️ Issues found"; fi)"

exit 0
