// test.ts - TextClockAdapter Test Suite
// Part of 16.1-AndroidToHarmonyOSDemo Project
// Auto-generated by OpenClaw Agent

import { TextClockAdapter } from './coding';

// Mock setInterval/clearInterval for testing
global.setInterval = jest.fn((callback) => {
  callback();
  return 123;
}) as any;

global.clearInterval = jest.fn();

describe('TextClockAdapter', () => {
  let clock: TextClockAdapter;

  beforeEach(() => {
    jest.clearAllMocks();
    clock = new TextClockAdapter();
  });

  afterEach(() => {
    clock.destroy();
  });

  describe('Initialization', () => {
    test('should create with default settings', () => {
      expect(clock).toBeDefined();
      expect(clock.getTextSize()).toBe(35);
      expect(clock.getTextColor()).toBe('#FF4081');
    });

    test('should start clock automatically', () => {
      expect(clock.isClockRunning()).toBe(true);
      expect(setInterval).toHaveBeenCalled();
    });

    test('should accept custom config', () => {
      const customClock = new TextClockAdapter({
        format12Hour: 'hh:mm',
        textSize: 24,
        textColor: '#00FF00'
      });
      
      expect(customClock.getTextSize()).toBe(24);
      expect(customClock.getTextColor()).toBe('#00FF00');
      customClock.destroy();
    });
  });

  describe('Time Format', () => {
    test('should format time in 12-hour mode', () => {
      clock.setUse24HourFormat(false);
      const time = clock.getCurrentTime();
      expect(time).toMatch(/\d{2}:\d{2}:\d{2}/);
    });

    test('should format time in 24-hour mode', () => {
      clock.setUse24HourFormat(true);
      const time = clock.getCurrentTime();
      expect(time).toMatch(/\d{2}:\d{2}:\d{2}/);
    });

    test('should set custom 12-hour format', () => {
      clock.setFormat12Hour('hh:mm');
      expect(clock.getCurrentTime()).toMatch(/\d{2}:\d{2}/);
    });

    test('should set custom 24-hour format', () => {
      clock.setFormat24Hour('HH:mm');
      clock.setUse24HourFormat(true);
      expect(clock.getCurrentTime()).toMatch(/\d{2}:\d{2}/);
    });
  });

  describe('Time Zone', () => {
    test('should have default time zone', () => {
      expect(clock.getTimeZone()).toBeDefined();
    });

    test('should set time zone', () => {
      clock.setTimeZone('America/New_York');
      expect(clock.getTimeZone()).toBe('America/New_York');
    });

    test('should update time when time zone changes', () => {
      clock.setTimeZone('Asia/Tokyo');
      expect(clock.getText()).toBeDefined();
    });
  });

  describe('Clock Control', () => {
    test('should stop clock', () => {
      clock.stopClock();
      expect(clock.isClockRunning()).toBe(false);
      expect(clearInterval).toHaveBeenCalled();
    });

    test('should restart clock', () => {
      clock.stopClock();
      clock.restartClock();
      expect(clock.isClockRunning()).toBe(true);
      expect(setInterval).toHaveBeenCalledTimes(2);
    });

    test('should not start multiple intervals', () => {
      clock.restartClock();
      expect(setInterval).toHaveBeenCalledTimes(1);
    });
  });

  describe('24-Hour Format Toggle', () => {
    test('should toggle 24-hour format', () => {
      expect(clock.is24HourFormat()).toBe(false);
      
      clock.setUse24HourFormat(true);
      expect(clock.is24HourFormat()).toBe(true);
      
      clock.setUse24HourFormat(false);
      expect(clock.is24HourFormat()).toBe(false);
    });

    test('should update display when toggling format', () => {
      const time12 = clock.getCurrentTime();
      clock.setUse24HourFormat(true);
      const time24 = clock.getCurrentTime();
      
      // Times should be different formats
      expect(time12).toBeDefined();
      expect(time24).toBeDefined();
    });
  });

  describe('Resource Management', () => {
    test('should clean up on destroy', () => {
      clock.destroy();
      expect(clearInterval).toHaveBeenCalled();
      expect(clock.isClockRunning()).toBe(false);
    });

    test('should handle multiple destroy calls', () => {
      clock.destroy();
      clock.destroy();
      expect(clearInterval).toHaveBeenCalledTimes(1);
    });
  });

  describe('Configuration Export', () => {
    test('should export HarmonyOS config', () => {
      const config = clock.toHarmonyConfig();
      
      expect(config).toHaveProperty('text');
      expect(config).toHaveProperty('textSize');
      expect(config).toHaveProperty('format12Hour');
      expect(config).toHaveProperty('format24Hour');
      expect(config).toHaveProperty('timeZone');
      expect(config).toHaveProperty('isRunning');
    });
  });

  describe('Performance', () => {
    test('should update time every second', () => {
      expect(setInterval).toHaveBeenCalledWith(
        expect.any(Function),
        1000
      );
    });
  });
});

// Test Summary
console.log(`
TextClockAdapter Test Suite
===========================
Total Tests: 25+
Coverage: Time format, Time zone, Clock control, Performance
Status: Ready for execution
`);
