#!/bin/bash
# setup-android-env.sh - Setup Android SDK in WSL2
# Auto-generated by OpenClaw Agent

set -e

echo "=========================================="
echo "Android SDK 安装脚本"
echo "=========================================="
echo ""

# 配置
ANDROID_SDK_ROOT="$HOME/Android/Sdk"
JDK_VERSION="11"

echo "[1/5] 安装 OpenJDK $JDK_VERSION..."
if ! command -v java &> /dev/null; then
    sudo apt-get update
    sudo apt-get install -y openjdk-${JDK_VERSION}-jdk
    echo "✓ JDK 安装完成"
else
    echo "✓ JDK 已安装: $(java -version 2>&1 | head -1)"
fi

echo ""
echo "[2/5] 下载 Android SDK..."
if [ ! -d "$ANDROID_SDK_ROOT" ]; then
    mkdir -p "$ANDROID_SDK_ROOT"
    cd /tmp
    
    # 下载 command line tools
    if [ ! -f "commandlinetools-linux-9477386_latest.zip" ]; then
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
    fi
    
    unzip -q commandlinetools-linux-9477386_latest.zip
    mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
    mv cmdline-tools "$ANDROID_SDK_ROOT/cmdline-tools/latest"
    
    echo "✓ Android SDK 下载完成"
else
    echo "✓ Android SDK 已存在"
fi

echo ""
echo "[3/5] 配置环境变量..."
ENV_FILE="$HOME/.bashrc"
if ! grep -q "ANDROID_HOME" "$ENV_FILE"; then
    cat >> "$ENV_FILE" << EOF

# Android SDK
export ANDROID_HOME=$ANDROID_SDK_ROOT
export PATH=\$PATH:\$ANDROID_HOME/cmdline-tools/latest/bin
export PATH=\$PATH:\$ANDROID_HOME/platform-tools
EOF
    echo "✓ 环境变量已添加到 $ENV_FILE"
else
    echo "✓ 环境变量已配置"
fi

# 立即生效
export ANDROID_HOME=$ANDROID_SDK_ROOT
export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

echo ""
echo "[4/5] 安装 Android SDK 组件..."

# 接受许可证
yes | sdkmanager --licenses > /dev/null 2>&1 || true

# 安装必要组件
sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3" "emulator"

echo "✓ SDK 组件安装完成"

echo ""
echo "[5/5] 验证安装..."
echo "  Java: $(java -version 2>&1 | head -1)"
echo "  ADB: $(adb version 2>&1 | head -1)"
echo "  SDK: $ANDROID_HOME"

echo ""
echo "=========================================="
echo "Android SDK 安装完成!"
echo "=========================================="
echo ""
echo "请运行: source ~/.bashrc"
echo ""
