#!/usr/bin/env node
// test-runner.js - Visual Test Runner with HTML Report
// Auto-generated by OpenClaw Agent

const fs = require('fs');
const path = require('path');

// Test results storage
const results = {
  total: 0,
  passed: 0,
  failed: 0,
  suites: []
};

let currentSuite = null;

function describe(name, fn) {
  currentSuite = { name, tests: [], passed: 0, failed: 0 };
  fn();
  results.suites.push(currentSuite);
  currentSuite = null;
}

function test(name, fn) {
  results.total++;
  const testResult = { name, status: 'passed', error: null };
  
  try {
    fn();
    results.passed++;
    currentSuite.passed++;
    testResult.status = 'passed';
    process.stdout.write('✅');
  } catch (error) {
    results.failed++;
    currentSuite.failed++;
    testResult.status = 'failed';
    testResult.error = error.message;
    process.stdout.write('❌');
  }
  
  currentSuite.tests.push(testResult);
}

function expect(actual) {
  return {
    toBe(expected) {
      if (actual !== expected) throw new Error(`Expected ${expected}, got ${actual}`);
    },
    toEqual(expected) {
      if (JSON.stringify(actual) !== JSON.stringify(expected)) {
        throw new Error(`Expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`);
      }
    },
    toBeDefined() {
      if (actual === undefined) throw new Error('Expected value to be defined');
    },
    toContain(expected) {
      if (!actual.includes(expected)) throw new Error(`Expected to contain "${expected}"`);
    }
  };
}

// Adapter implementations
class BundleAdapter {
  constructor(wantParams) {
    this.params = new Map();
    if (wantParams) {
      Object.entries(wantParams).forEach(([key, value]) => {
        this.params.set(key, value);
      });
    }
  }
  put(key, value) { this.params.set(key, value); }
  get(key) { return this.params.get(key); }
  getString(key, defaultValue) {
    const value = this.params.get(key);
    return value !== undefined ? String(value) : defaultValue;
  }
  getInt(key, defaultValue) {
    const value = this.params.get(key);
    return value !== undefined ? parseInt(value, 10) : defaultValue;
  }
  containsKey(key) { return this.params.has(key); }
  keySet() { return Array.from(this.params.keys()); }
  isEmpty() { return this.params.size === 0; }
  size() { return this.params.size; }
  toWantParams() {
    const result = {};
    this.params.forEach((value, key) => { result[key] = value; });
    return result;
  }
}

class ButtonAdapter {
  constructor(text = '') {
    this.text = text;
    this.enabled = true;
    this.clickListener = null;
  }
  setText(text) { this.text = text; }
  getText() { return this.text; }
  setEnabled(enabled) { this.enabled = enabled; }
  isEnabled() { return this.enabled; }
  setOnClickListener(listener) { this.clickListener = listener; }
  performClick() {
    if (this.clickListener && this.enabled) this.clickListener();
  }
}

class TextViewAdapter {
  constructor(text = '') {
    this.text = text;
    this.textSize = 16;
  }
  setText(text) { this.text = String(text); }
  getText() { return this.text; }
  setTextSize(size) { this.textSize = size; }
  getTextSize() { return this.textSize; }
}

class TimeZoneAdapter {
  constructor(timeZoneId) {
    this.timeZoneId = timeZoneId || 'UTC';
  }
  static getDefault() {
    return new TimeZoneAdapter('Asia/Shanghai');
  }
  getID() { return this.timeZoneId; }
  getDisplayName() { return 'CST'; }
}

class EventAdapter {
  constructor() {
    this.listeners = new Map();
  }
  setOnClickListener(id, listener) {
    if (!this.listeners.has(id)) {
      this.listeners.set(id, []);
    }
    this.listeners.get(id).push(listener);
  }
  triggerClick(id) {
    const listeners = this.listeners.get(id) || [];
    listeners.forEach(listener => listener());
  }
}

// Run tests
console.log('\n🚀 Starting 131 Project Tests\n');
console.log('Running: ');

// BundleAdapter Tests
describe('BundleAdapter', () => {
  test('create empty bundle', () => {
    const bundle = new BundleAdapter();
    expect(bundle.isEmpty()).toBe(true);
  });
  test('put and get string', () => {
    const bundle = new BundleAdapter();
    bundle.put('name', 'John');
    expect(bundle.getString('name')).toBe('John');
  });
  test('put and get int', () => {
    const bundle = new BundleAdapter();
    bundle.put('age', 25);
    expect(bundle.getInt('age')).toBe(25);
  });
  test('default value', () => {
    const bundle = new BundleAdapter();
    expect(bundle.getString('missing', 'default')).toBe('default');
  });
  test('check key existence', () => {
    const bundle = new BundleAdapter();
    bundle.put('key', 'value');
    expect(bundle.containsKey('key')).toBe(true);
  });
  test('convert to wantParams', () => {
    const bundle = new BundleAdapter();
    bundle.put('a', 1);
    expect(bundle.toWantParams()).toEqual({ a: 1 });
  });
});

// ButtonAdapter Tests
describe('ButtonAdapter', () => {
  test('set and get text', () => {
    const btn = new ButtonAdapter();
    btn.setText('Click');
    expect(btn.getText()).toBe('Click');
  });
  test('handle click', () => {
    const btn = new ButtonAdapter();
    let clicked = false;
    btn.setOnClickListener(() => { clicked = true; });
    btn.performClick();
    expect(clicked).toBe(true);
  });
  test('respect enabled state', () => {
    const btn = new ButtonAdapter();
    let clicked = false;
    btn.setOnClickListener(() => { clicked = true; });
    btn.setEnabled(false);
    btn.performClick();
    expect(clicked).toBe(false);
  });
});

// TextViewAdapter Tests
describe('TextViewAdapter', () => {
  test('set and get text', () => {
    const tv = new TextViewAdapter();
    tv.setText('Hello');
    expect(tv.getText()).toBe('Hello');
  });
  test('set and get text size', () => {
    const tv = new TextViewAdapter();
    tv.setTextSize(24);
    expect(tv.getTextSize()).toBe(24);
  });
});

// TimeZoneAdapter Tests
describe('TimeZoneAdapter', () => {
  test('create with default', () => {
    const tz = TimeZoneAdapter.getDefault();
    expect(tz.getID()).toBeDefined();
  });
  test('create with specific', () => {
    const tz = new TimeZoneAdapter('America/New_York');
    expect(tz.getID()).toBe('America/New_York');
  });
  test('get display name', () => {
    const tz = new TimeZoneAdapter('UTC');
    expect(tz.getDisplayName()).toBeDefined();
  });
});

// EventAdapter Tests
describe('EventAdapter', () => {
  test('register and trigger', () => {
    const events = new EventAdapter();
    let clicked = false;
    events.setOnClickListener('btn', () => { clicked = true; });
    events.triggerClick('btn');
    expect(clicked).toBe(true);
  });
  test('multiple listeners', () => {
    const events = new EventAdapter();
    let count = 0;
    events.setOnClickListener('btn', () => { count++; });
    events.setOnClickListener('btn', () => { count++; });
    events.triggerClick('btn');
    expect(count).toBe(2);
  });
});

// Integration Tests
describe('Integration', () => {
  test('TextClock activity', () => {
    const bundle = new BundleAdapter();
    const tv = new TextViewAdapter();
    const btn = new ButtonAdapter();
    const events = new EventAdapter();
    
    events.setOnClickListener('tz', () => {
      tv.setText('Zone: ' + TimeZoneAdapter.getDefault().getDisplayName());
    });
    btn.setOnClickListener(() => events.triggerClick('tz'));
    btn.performClick();
    
    expect(tv.getText()).toContain('Zone:');
  });
  test('lifecycle', () => {
    const bundle = new BundleAdapter();
    bundle.put('key', 'value');
    expect(bundle.getString('key')).toBe('value');
  });
});

console.log('\n\n');

// Print summary
console.log('========================================');
console.log('📊 Test Summary');
console.log('========================================');
console.log(`Total:  ${results.total}`);
console.log(`✅ Passed: ${results.passed}`);
console.log(`❌ Failed: ${results.failed}`);
console.log(`Success: ${Math.round((results.passed / results.total) * 100)}%`);
console.log('========================================\n');

// Print detailed results
console.log('📋 Detailed Results:\n');
results.suites.forEach(suite => {
  const icon = suite.failed === 0 ? '✅' : '⚠️';
  console.log(`${icon} ${suite.name} (${suite.passed}/${suite.tests.length})`);
  suite.tests.forEach(test => {
    const statusIcon = test.status === 'passed' ? '  ✅' : '  ❌';
    console.log(`${statusIcon} ${test.name}`);
    if (test.error) {
      console.log(`      Error: ${test.error}`);
    }
  });
  console.log('');
});

// Generate HTML report
const htmlReport = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>131 Project Test Report</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; background: #f5f5f5; }
    .header { background: #333; color: white; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
    .summary { background: white; padding: 20px; border-radius: 8px; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
    .suite { background: white; padding: 15px; margin-bottom: 15px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
    .suite-header { font-size: 18px; font-weight: bold; margin-bottom: 10px; color: #333; }
    .test { padding: 8px; margin: 5px 0; border-radius: 4px; }
    .passed { background: #d4edda; color: #155724; }
    .failed { background: #f8d7da; color: #721c24; }
    .stats { display: flex; gap: 20px; margin-top: 15px; }
    .stat-box { background: #f8f9fa; padding: 15px; border-radius: 8px; text-align: center; flex: 1; }
    .stat-number { font-size: 32px; font-weight: bold; color: #333; }
    .stat-label { color: #666; margin-top: 5px; }
    .success { color: #28a745; }
    .error { color: #dc3545; }
  </style>
</head>
<body>
  <div class="header">
    <h1>🚀 16.1-AndroidToHarmonyOSDemo Test Report</h1>
    <p>Generated: ${new Date().toLocaleString()}</p>
  </div>
  
  <div class="summary">
    <h2>📊 Summary</h2>
    <div class="stats">
      <div class="stat-box">
        <div class="stat-number">${results.total}</div>
        <div class="stat-label">Total Tests</div>
      </div>
      <div class="stat-box">
        <div class="stat-number success">${results.passed}</div>
        <div class="stat-label">Passed</div>
      </div>
      <div class="stat-box">
        <div class="stat-number error">${results.failed}</div>
        <div class="stat-label">Failed</div>
      </div>
      <div class="stat-box">
        <div class="stat-number">${Math.round((results.passed / results.total) * 100)}%</div>
        <div class="stat-label">Success Rate</div>
      </div>
    </div>
  </div>
  
  <h2>📋 Test Suites</h2>
  ${results.suites.map(suite => `
    <div class="suite">
      <div class="suite-header">
        ${suite.failed === 0 ? '✅' : '⚠️'} ${suite.name}
        <span style="float: right; color: #666;">${suite.passed}/${suite.tests.length}</span>
      </div>
      ${suite.tests.map(test => `
        <div class="test ${test.status}">
          ${test.status === 'passed' ? '✅' : '❌'} ${test.name}
          ${test.error ? `<br><small style="color: #721c24;">Error: ${test.error}</small>` : ''}
        </div>
      `).join('')}
    </div>
  `).join('')}
  
  <div style="text-align: center; margin-top: 40px; color: #666;">
    <p>16.1-AndroidToHarmonyOSDemo Project | Auto-generated by OpenClaw Agent</p>
  </div>
</body>
</html>
`;

const reportPath = path.join(__dirname, 'test-report.html');
fs.writeFileSync(reportPath, htmlReport);
console.log(`📄 HTML Report saved: ${reportPath}`);

// Exit with appropriate code
process.exit(results.failed > 0 ? 1 : 0);
