#!/bin/bash
# review-131.sh - 131项目代码审查脚本
# Auto-generated by OpenClaw Agent

echo "=========================================="
echo "131项目代码审查 - 识别LLM幻觉"
echo "=========================================="
echo ""

PROJECT_DIR="/mnt/d/ObsidianVault/10-Projects/16-DigitalEmployee/16.1-AndroidToHarmonyOSDemo"
ADAPTER_DIR="$PROJECT_DIR/16.1.2-ADAPTER-DEVELOPMENT"
REPORT_FILE="$PROJECT_DIR/16.1-CODE-REVIEW-REPORT.md"

ERRORS=0
WARNINGS=0
SUGGESTIONS=0

# 初始化报告
cat > "$REPORT_FILE" << 'EOF'
---
tags:
  - project/dev
  - code-review
  - llm-hallucination
date: 2026-03-09
---

# 131项目代码审查报告

**审查时间**: $(date '+%Y-%m-%d %H:%M:%S')  
**审查者**: OpenClaw Agent  
**审查范围**: 10个Adapter, ~2000行代码

---

## 执行摘要

EOF

echo "[1/6] 检查文件完整性..."
REQUIRED_ADAPTERS=(
  "16.1.20-BUNDLE-ADAPTER"
  "16.1.20-APPCOMPAT-ADAPTER"
  "16.1.21-SETCONTENTVIEW-ADAPTER"
  "16.1.21-FINDVIEWBYID-ADAPTER"
  "16.1.21-BUTTON-ADAPTER"
  "16.1.22-TEXTVIEW-ADAPTER"
  "16.1.22-TEXTCLOCK-ADAPTER"
  "16.1.22-TIMEZONE-ADAPTER"
  "16.1.23-ONCLICK-ADAPTER"
  "16.1.23-CONSTRAINT-ADAPTER"
)

MISSING_ADAPTERS=0
for adapter in "${REQUIRED_ADAPTERS[@]}"; do
  if [ -d "$ADAPTER_DIR/$adapter" ]; then
    if [ -f "$ADAPTER_DIR/$adapter/coding.ts" ]; then
      echo "  ✅ $adapter/coding.ts"
    else
      echo "  ❌ $adapter/coding.ts (缺失)"
      ERRORS=$((ERRORS + 1))
      MISSING_ADAPTERS=$((MISSING_ADAPTERS + 1))
    fi
    
    if [ -f "$ADAPTER_DIR/$adapter/test.ts" ]; then
      echo "  ✅ $adapter/test.ts"
    else
      echo "  ⚠️  $adapter/test.ts (缺失)"
      WARNINGS=$((WARNINGS + 1))
    fi
  else
    echo "  ❌ $adapter (目录缺失)"
    ERRORS=$((ERRORS + 1))
    MISSING_ADAPTERS=$((MISSING_ADAPTERS + 1))
  fi
done

echo ""
echo "[2/6] 检查常见LLM幻觉模式..."

# 检查1: Android API直接复制
ANDROID_APIS=(
  "android.os.Bundle"
  "android.widget.Button"
  "android.widget.TextView"
  "android.app.Activity"
  "android.view.View"
)

HALLUCINATION_COUNT=0
for api in "${ANDROID_APIS[@]}"; do
  count=$(grep -r "$api" "$ADAPTER_DIR"/*/coding.ts 2>/dev/null | wc -l)
  if [ $count -gt 0 ]; then
    echo "  ⚠️  发现Android API引用: $api ($count处)"
    HALLUCINATION_COUNT=$((HALLUCINATION_COUNT + count))
    WARNINGS=$((WARNINGS + 1))
  fi
done

if [ $HALLUCINATION_COUNT -eq 0 ]; then
  echo "  ✅ 未发现直接Android API导入"
fi

# 检查2: 不存在的HarmonyOS API
SUSPICIOUS_APIS=(
  "@ohos.arkui.Bundle"
  "@ohos.arkui.Activity"
  "@ohos.arkui.TextClock"
)

for api in "${SUSPICIOUS_APIS[@]}"; do
  count=$(grep -r "$api" "$ADAPTER_DIR"/*/coding.ts 2>/dev/null | wc -l)
  if [ $count -gt 0 ]; then
    echo "  🔴 可疑API导入: $api ($count处) - 可能不存在"
    ERRORS=$((ERRORS + 1))
  fi
done

echo ""
echo "[3/6] 检查类型定义..."

# 检查any类型
ANY_COUNT=$(grep -r ": any" "$ADAPTER_DIR"/*/coding.ts 2>/dev/null | wc -l)
if [ $ANY_COUNT -gt 0 ]; then
  echo "  ⚠️  发现 $ANY_COUNT 个any类型，建议细化"
  WARNINGS=$((WARNINGS + 1))
else
  echo "  ✅ 未发现any类型"
fi

# 检查undefined处理
UNDEFINED_COUNT=$(grep -r "| undefined" "$ADAPTER_DIR"/*/coding.ts 2>/dev/null | wc -l)
echo "  ℹ️  发现 $UNDEFINED_COUNT 个可能为undefined的返回类型"

echo ""
echo "[4/6] 检查生命周期映射..."

# 检查Android生命周期方法
ANDROID_LIFECYCLE=(
  "onCreate("
  "onStart("
  "onResume("
  "onPause("
  "onStop("
  "onDestroy("
)

for method in "${ANDROID_LIFECYCLE[@]}"; do
  count=$(grep -r "$method" "$ADAPTER_DIR"/*/coding.ts 2>/dev/null | wc -l)
  if [ $count -gt 0 ]; then
    echo "  ℹ️  发现Android生命周期方法: $method ($count处)"
    echo "     注意: 需要映射到HarmonyOS生命周期"
  fi
done

echo ""
echo "[5/6] 检查测试覆盖率..."

TEST_COUNT=$(find "$ADAPTER_DIR" -name "test.ts" | wc -l)
ADAPTER_COUNT=$(find "$ADAPTER_DIR" -name "coding.ts" | wc -l)

echo "  Adapter数量: $ADAPTER_COUNT"
echo "  测试文件数量: $TEST_COUNT"

if [ $TEST_COUNT -eq $ADAPTER_COUNT ]; then
  echo "  ✅ 每个Adapter都有测试文件"
else
  echo "  ⚠️  测试覆盖率不完整: $TEST_COUNT/$ADAPTER_COUNT"
  WARNINGS=$((WARNINGS + 1))
fi

# 统计测试用例
TEST_CASES=$(grep -h "test(" "$ADAPTER_DIR"/*/test.ts 2>/dev/null | wc -l)
echo "  测试用例总数: $TEST_CASES"

echo ""
echo "[6/6] 代码统计..."

TOTAL_LINES=$(find "$ADAPTER_DIR" -name "*.ts" -exec wc -l {} + 2>/dev/null | tail -1 | awk '{print $1}')
CODE_LINES=$(find "$ADAPTER_DIR" -name "coding.ts" -exec wc -l {} + 2>/dev/null | tail -1 | awk '{print $1}')
TEST_LINES=$(find "$ADAPTER_DIR" -name "test.ts" -exec wc -l {} + 2>/dev/null | tail -1 | awk '{print $1}')

echo "  总代码行数: $TOTAL_LINES"
echo "  实现代码: $CODE_LINES"
echo "  测试代码: $TEST_LINES"
echo "  测试比例: $(($TEST_LINES * 100 / $CODE_LINES))%"

# 生成报告
cat >> "$REPORT_FILE" << EOF
| 指标 | 数值 | 状态 |
|------|------|------|
| Adapter数量 | $ADAPTER_COUNT | ✅ |
| 测试文件数 | $TEST_COUNT | ✅ |
| 测试用例数 | $TEST_CASES | ✅ |
| 总代码行数 | $TOTAL_LINES | - |
| 错误数 | $ERRORS | $(if [ $ERRORS -eq 0 ]; then echo "✅"; else echo "❌"; fi) |
| 警告数 | $WARNINGS | $(if [ $WARNINGS -eq 0 ]; then echo "✅"; else echo "⚠️"; fi) |

---

## 详细发现

### 🔴 错误 (需要修复)

$(if [ $ERRORS -eq 0 ]; then echo "无"; else echo "发现 $ERRORS 个问题"; fi)

### ⚠️ 警告 (建议改进)

$(if [ $WARNINGS -eq 0 ]; then echo "无"; else echo "发现 $WARNINGS 个问题"; fi)

- any类型使用: $ANY_COUNT 处
- Android API引用: $HALLUCINATION_COUNT 处

### ℹ️ 提示

- 测试代码比例: $(($TEST_LINES * 100 / $CODE_LINES))%
- 未定义返回类型: $UNDEFINED_COUNT 处

---

## 建议修复

### 高优先级
1. 检查并替换不存在的HarmonyOS API导入
2. 细化any类型为具体类型
3. 验证生命周期方法映射

### 中优先级
1. 补充缺失的测试文件
2. 添加更多边界条件测试
3. 完善错误处理

### 低优先级
1. 代码格式统一
2. 注释完善
3. 性能优化

---

## 结论

$(if [ $ERRORS -eq 0 ] && [ $WARNINGS -lt 5 ]; then echo "✅ **代码审查通过** - 质量良好，可以进入下一阶段"; elif [ $ERRORS -eq 0 ]; then echo "⚠️ **代码审查有条件通过** - 需要修复警告后进入下一阶段"; else echo "❌ **代码审查未通过** - 需要修复错误后重新审查"; fi)

---

**生成时间**: $(date '+%Y-%m-%d %H:%M:%S')  
**审查脚本**: review-131.sh
EOF

echo ""
echo "=========================================="
echo "审查完成!"
echo "=========================================="
echo ""
echo "错误: $ERRORS"
echo "警告: $WARNINGS"
echo "建议: $SUGGESTIONS"
echo ""
echo "详细报告: $REPORT_FILE"

if [ $ERRORS -eq 0 ] && [ $WARNINGS -lt 5 ]; then
  echo "✅ 代码质量良好"
elif [ $ERRORS -eq 0 ]; then
  echo "⚠️  需要修复警告"
else
  echo "❌ 需要修复错误"
fi

exit 0
