// coding.ts - TextViewAdapter Implementation
// Part of 16.1-AndroidToHarmonyOSDemo Project
// Auto-generated by OpenClaw Agent

/**
 * Adapter for Android TextView → HarmonyOS Text
 * 
 * Android: android.widget.TextView
 * HarmonyOS: Text (ArkUI)
 * 
 * Complexity: ⭐ Low
 * Estimated Time: 4 hours
 * Status: ✅ Implemented
 */

export interface TextViewConfig {
  text?: string;
  textSize?: number;
  textColor?: string;
  width?: string | number;
  height?: string | number;
}

/**
 * TextViewAdapter - Text display component adapter
 * 
 * Provides Android TextView compatibility for HarmonyOS
 */
export class TextViewAdapter {
  private config: TextViewConfig;
  private textValue: string = '';
  private textSizeValue: number = 16;
  private textColorValue: string = '#000000';
  private widthValue: string | number = 'wrap_content';
  private heightValue: string | number = 'wrap_content';
  private clickListener?: () => void;
  
  constructor(config: TextViewConfig = {}) {
    this.config = config;
    this.textValue = config.text || '';
    this.textSizeValue = config.textSize || 16;
    this.textColorValue = config.textColor || '#000000';
    this.widthValue = config.width || 'wrap_content';
    this.heightValue = config.height || 'wrap_content';
  }
  
  /**
   * Set the text to display
   * Maps to: TextView.setText()
   */
  setText(text: string | number): void {
    this.textValue = String(text);
  }
  
  /**
   * Get the displayed text
   * Maps to: TextView.getText()
   */
  getText(): string {
    return this.textValue;
  }
  
  /**
   * Set text size
   * Maps to: TextView.setTextSize()
   */
  setTextSize(size: number): void {
    this.textSizeValue = size;
  }
  
  /**
   * Get text size
   */
  getTextSize(): number {
    return this.textSizeValue;
  }
  
  /**
   * Set text color
   * Maps to: TextView.setTextColor()
   */
  setTextColor(color: string): void {
    this.textColorValue = color;
  }
  
  /**
   * Get text color
   */
  getTextColor(): string {
    return this.textColorValue;
  }
  
  /**
   * Set width
   */
  setWidth(width: string | number): void {
    this.widthValue = width;
  }
  
  /**
   * Set height
   */
  setHeight(height: string | number): void {
    this.heightValue = height;
  }
  
  /**
   * Append text
   * Maps to: TextView.append()
   */
  append(text: string): void {
    this.textValue += text;
  }
  
  /**
   * Set click listener
   * Maps to: TextView.setOnClickListener()
   */
  setOnClickListener(listener: () => void): void {
    this.clickListener = listener;
  }
  
  /**
   * Trigger click
   */
  performClick(): void {
    if (this.clickListener) {
      this.clickListener();
    }
  }
  
  /**
   * Convert to HarmonyOS Text configuration
   */
  toHarmonyConfig(): TextViewConfig {
    return {
      text: this.textValue,
      textSize: this.textSizeValue,
      textColor: this.textColorValue,
      width: this.widthValue,
      height: this.heightValue
    };
  }
  
  /**
   * Create HarmonyOS Text component
   */
  createHarmonyText(): any {
    // Returns configuration for HarmonyOS Text component
    return this.toHarmonyConfig();
  }
}

// Export for module usage
export default TextViewAdapter;
