#!/bin/bash
# 16.1.101 - Download TextClock PoC Project
# Auto-generated by OpenClaw Agent
# Date: 2026-03-09

set -e

PROJECT_DIR="/mnt/d/ObsidianVault/10-Projects/16-DigitalEmployee/16.1-AndroidToHarmonyOSDemo"
DOWNLOAD_DIR="$PROJECT_DIR/16.1.1-ANDROID-ANALYSIS/16.1.10-POC-DOWNLOAD"
REPORT_FILE="$DOWNLOAD_DIR/download-report.md"

# GitHub repository URL
REPO_URL="https://github.com/Darrel-Asare/Homework2.git"
PROJECT_NAME="TextClock"

echo "=========================================="
echo "16.1.101 - Download TextClock PoC"
echo "=========================================="
echo ""

# Create download directory
mkdir -p "$DOWNLOAD_DIR"
cd "$DOWNLOAD_DIR"

# Record start time
START_TIME=$(date +%s)

echo "[1/4] Cloning repository..."
if git clone "$REPO_URL" "$PROJECT_NAME"; then
    echo "✓ Repository cloned successfully"
else
    echo "✗ Failed to clone repository"
    exit 1
fi

echo ""
echo "[2/4] Verifying project structure..."
cd "$PROJECT_NAME"

# Check required files
REQUIRED_FILES=(
    "app/src/main/java/com/w/homework2/MainActivity.java"
    "app/src/main/res/layout/activity_main.xml"
    "AndroidManifest.xml"
    "build.gradle"
)

MISSING_FILES=0
for file in "${REQUIRED_FILES[@]}"; do
    if [ -f "$file" ]; then
        echo "  ✓ $file"
    else
        echo "  ✗ $file (missing)"
        MISSING_FILES=$((MISSING_FILES + 1))
    fi
done

echo ""
echo "[3/4] Calculating statistics..."

# Count lines of code
JAVA_LINES=$(find . -name "*.java" -type f -exec wc -l {} + 2>/dev/null | tail -1 | awk '{print $1}')
XML_LINES=$(find . -name "*.xml" -type f -exec wc -l {} + 2>/dev/null | tail -1 | awk '{print $1}')
TOTAL_LINES=$((JAVA_LINES + XML_LINES))

# Calculate project size
PROJECT_SIZE=$(du -sh . | cut -f1)

# Count files
FILE_COUNT=$(find . -type f | wc -l)

echo "  Java files: $JAVA_LINES lines"
echo "  XML files: $XML_LINES lines"
echo "  Total: $TOTAL_LINES lines"
echo "  Project size: $PROJECT_SIZE"
echo "  Total files: $FILE_COUNT"

# Record end time
END_TIME=$(date +%s)
DURATION=$((END_TIME - START_TIME))

echo ""
echo "[4/4] Generating report..."

# Generate markdown report
cat > "$REPORT_FILE" << EOF
---
tags:
  - project/dev
  - android
  - poc-download
date: $(date +%Y-%m-%d)
status: completed
---

# Download Report - TextClock PoC

## Summary

| Metric | Value |
|--------|-------|
| **Repository** | $REPO_URL |
| **Project Name** | $PROJECT_NAME |
| **Download Date** | $(date '+%Y-%m-%d %H:%M:%S') |
| **Duration** | $DURATION seconds |
| **Status** | ✅ Success |

## Project Statistics

| Metric | Value |
|--------|-------|
| **Java Lines** | $JAVA_LINES |
| **XML Lines** | $XML_LINES |
| **Total Lines** | $TOTAL_LINES |
| **Project Size** | $PROJECT_SIZE |
| **Total Files** | $FILE_COUNT |

## File Structure

\`\`\`
$(tree -L 3 -I '.git|.idea' "$PROJECT_NAME" 2>/dev/null || find "$PROJECT_NAME" -maxdepth 3 -type f | head -30)
\`\`\`

## Verification

| File | Status |
|------|--------|
EOF

for file in "${REQUIRED_FILES[@]}"; do
    if [ -f "$PROJECT_NAME/$file" ]; then
        echo "| $file | ✅ |" >> "$REPORT_FILE"
    else
        echo "| $file | ❌ |" >> "$REPORT_FILE"
    fi
done

cat >> "$REPORT_FILE" << EOF

## Missing Files

Missing files count: $MISSING_FILES

## Next Steps

1. ✅ Download complete
2. ⏳ Verify integrity (16.1.102)
3. ⏳ Configure Android SDK (16.1.111)
4. ⏳ Build APK (16.1.113)

---

**Generated**: $(date '+%Y-%m-%d %H:%M:%S')  
**Script**: 16.1.101-download_textclock.sh
EOF

echo "✓ Report generated: $REPORT_FILE"

echo ""
echo "=========================================="
echo "Download Complete!"
echo "=========================================="
echo "Duration: $DURATION seconds"
echo "Location: $DOWNLOAD_DIR/$PROJECT_NAME"
echo "Report: $REPORT_FILE"

# Return to project directory
cd "$PROJECT_DIR"

exit 0
