#!/bin/bash
# 16.1.113 - Build APK Script
# Auto-generated by OpenClaw Agent

set -e

PROJECT_DIR="/mnt/d/ObsidianVault/10-Projects/16-DigitalEmployee/16.1-AndroidToHarmonyOSDemo"
PROJECT_PATH="$PROJECT_DIR/16.1.1-ANDROID-ANALYSIS/16.1.10-POC-DOWNLOAD/TextClock"
BUILD_DIR="$PROJECT_DIR/16.1.1-ANDROID-ANALYSIS/16.1.11-ANDROID-BUILD"
REPORT_FILE="$BUILD_DIR/build-report.md"

echo "=========================================="
echo "16.1.113 - Build TextClock APK"
echo "=========================================="
echo ""

mkdir -p "$BUILD_DIR"

if [ ! -d "$PROJECT_PATH" ]; then
    echo "✗ Project not found. Run 16.1.101 first."
    exit 1
fi

cd "$PROJECT_PATH"
START_TIME=$(date +%s)

echo "[1/5] Checking Gradle wrapper..."
if [ ! -f "./gradlew" ]; then
    echo "✗ Gradle wrapper not found"
    exit 1
fi
echo "✓ Gradle wrapper found"

echo ""
echo "[2/5] Making gradlew executable..."
chmod +x ./gradlew
echo "✓ gradlew is executable"

echo ""
echo "[3/5] Running Gradle build..."
BUILD_OUTPUT="$BUILD_DIR/build.log"

# Try to build
if ./gradlew assembleDebug --console=plain > "$BUILD_OUTPUT" 2>&1; then
    echo "✓ Build successful"
    BUILD_STATUS="SUCCESS"
else
    echo "✗ Build failed"
    BUILD_STATUS="FAILED"
    echo "Build log:"
    tail -50 "$BUILD_OUTPUT"
fi

echo ""
echo "[4/5] Checking for APK..."

APK_PATH="app/build/outputs/apk/debug/app-debug.apk"
if [ -f "$APK_PATH" ]; then
    APK_SIZE=$(ls -lh "$APK_PATH" | awk '{print $5}')
    echo "✓ APK found: $APK_SIZE"
    
    # Copy to build directory
    cp "$APK_PATH" "$BUILD_DIR/TextClock-debug.apk"
    echo "✓ APK copied to build directory"
else
    echo "⚠ APK not found at expected path"
    APK_SIZE="N/A"
fi

echo ""
echo "[5/5] Analyzing build..."

# Extract build info
if [ -f "$BUILD_OUTPUT" ]; then
    BUILD_TIME=$(grep "BUILD" "$BUILD_OUTPUT" | tail -1 || echo "Unknown")
    ERRORS=$(grep -c "ERROR" "$BUILD_OUTPUT" || echo "0")
    WARNINGS=$(grep -c "WARNING" "$BUILD_OUTPUT" || echo "0")
    
    echo "  Errors: $ERRORS"
    echo "  Warnings: $WARNINGS"
fi

END_TIME=$(date +%s)
DURATION=$((END_TIME - START_TIME))

echo ""
echo "=========================================="
echo "Generating report..."
echo "=========================================="

cat > "$REPORT_FILE" << EOF
---
tags:
  - project/dev
  - android
  - build
date: $(date +%Y-%m-%d)
status: $(echo "$BUILD_STATUS" | tr '[:upper:]' '[:lower:]')
---

# Build Report - TextClock APK

## Summary

| Metric | Value |
|--------|-------|
| **Project** | TextClock |
| **Build Type** | Debug |
| **Status** | $BUILD_STATUS |
| **Build Date** | $(date '+%Y-%m-%d %H:%M:%S') |
| **Duration** | $DURATION seconds |

## Build Statistics

| Metric | Value |
|--------|-------|
| **APK Size** | ${APK_SIZE:-N/A} |
| **Errors** | ${ERRORS:-0} |
| **Warnings** | ${WARNINGS:-0} |

## Output

| File | Path |
|------|------|
| Build Log | $BUILD_OUTPUT |
| APK | ${APK_PATH:-Not found} |
| Copied APK | $BUILD_DIR/TextClock-debug.apk |

## Build Log Excerpt

\`\`\`
$(tail -30 "$BUILD_OUTPUT" 2>/dev/null || echo "No log available")
\`\`\`

## Next Steps

1. ✅ Download (16.1.101)
2. ✅ Verify integrity (16.1.102)
3. ✅ Configure SDK (16.1.111)
4. ✅ Configure Gradle (16.1.112)
5. ✅ Build APK (16.1.113)
6. ⏳ Code analysis (16.1.121)

---

**Generated**: $(date '+%Y-%m-%d %H:%M:%S')  
**Script**: 16.1.113-build_apk.sh
EOF

echo "✓ Report generated: $REPORT_FILE"

echo ""
echo "=========================================="
echo "Build Complete!"
echo "=========================================="
echo "Duration: $DURATION seconds"
echo "Status: $BUILD_STATUS"
echo "APK: $BUILD_DIR/TextClock-debug.apk"

exit 0
