// coding.ts - BundleAdapter Implementation
// Part of 16.1-AndroidToHarmonyOSDemo Project
// Auto-generated by OpenClaw Agent

/**
 * Adapter for Android Bundle → HarmonyOS wantParams
 * 
 * Android: android.os.Bundle
 * HarmonyOS: wantParams (Record<string, any>)
 * 
 * Complexity: ⭐ Low
 * Estimated Time: 4 hours
 * Status: ✅ Implemented
 */

export class BundleAdapter {
  private params: Map<string, any> = new Map();

  /**
   * Create empty Bundle
   */
  constructor();
  
  /**
   * Create Bundle from existing wantParams
   */
  constructor(wantParams: Record<string, any>);
  
  constructor(wantParams?: Record<string, any>) {
    if (wantParams) {
      Object.entries(wantParams).forEach(([key, value]) => {
        this.params.set(key, value);
      });
    }
  }

  /**
   * Static factory method to create from wantParams
   * Maps to: Bundle.fromWantParams()
   */
  static fromWantParams(params: Record<string, any>): BundleAdapter {
    return new BundleAdapter(params);
  }

  /**
   * Put a value into the Bundle
   * Maps to: bundle.putString(), bundle.putInt(), etc.
   */
  put(key: string, value: any): void {
    this.params.set(key, value);
  }

  /**
   * Get a value from the Bundle
   * Maps to: bundle.get(), bundle.getString(), etc.
   */
  get(key: string): any | undefined {
    return this.params.get(key);
  }

  /**
   * Get string value
   */
  getString(key: string): string | undefined;
  getString(key: string, defaultValue: string): string;
  getString(key: string, defaultValue?: string): string | undefined {
    const value = this.params.get(key);
    if (value === undefined) {
      return defaultValue;
    }
    return String(value);
  }

  /**
   * Get integer value
   */
  getInt(key: string): number | undefined;
  getInt(key: string, defaultValue: number): number;
  getInt(key: string, defaultValue?: number): number | undefined {
    const value = this.params.get(key);
    if (value === undefined) {
      return defaultValue;
    }
    return parseInt(value, 10);
  }

  /**
   * Get boolean value
   */
  getBoolean(key: string): boolean | undefined;
  getBoolean(key: string, defaultValue: boolean): boolean;
  getBoolean(key: string, defaultValue?: boolean): boolean | undefined {
    const value = this.params.get(key);
    if (value === undefined) {
      return defaultValue;
    }
    return Boolean(value);
  }

  /**
   * Check if key exists
   * Maps to: bundle.containsKey()
   */
  containsKey(key: string): boolean {
    return this.params.has(key);
  }

  /**
   * Remove a key
   * Maps to: bundle.remove()
   */
  remove(key: string): void {
    this.params.delete(key);
  }

  /**
   * Clear all data
   * Maps to: bundle.clear()
   */
  clear(): void {
    this.params.clear();
  }

  /**
   * Get all keys
   * Maps to: bundle.keySet()
   */
  keySet(): string[] {
    return Array.from(this.params.keys());
  }

  /**
   * Check if empty
   * Maps to: bundle.isEmpty()
   */
  isEmpty(): boolean {
    return this.params.size === 0;
  }

  /**
   * Get size
   * Maps to: bundle.size()
   */
  size(): number {
    return this.params.size;
  }

  /**
   * Convert to wantParams for HarmonyOS
   */
  toWantParams(): Record<string, any> {
    const result: Record<string, any> = {};
    this.params.forEach((value, key) => {
      result[key] = value;
    });
    return result;
  }

  /**
   * Clone the Bundle
   * Maps to: bundle.clone()
   */
  clone(): BundleAdapter {
    const cloned = new BundleAdapter();
    this.params.forEach((value, key) => {
      cloned.put(key, value);
    });
    return cloned;
  }
}

// Export for module usage
export default BundleAdapter;
