// test.ts - TextViewAdapter Test Suite
// Part of 16.1-AndroidToHarmonyOSDemo Project
// Auto-generated by OpenClaw Agent

import { TextViewAdapter } from './coding';

describe('TextViewAdapter', () => {
  let textView: TextViewAdapter;

  beforeEach(() => {
    textView = new TextViewAdapter();
  });

  describe('Text Management', () => {
    test('should set and get text', () => {
      textView.setText('Hello World');
      expect(textView.getText()).toBe('Hello World');
    });

    test('should handle number as text', () => {
      textView.setText(42);
      expect(textView.getText()).toBe('42');
    });

    test('should append text', () => {
      textView.setText('Hello');
      textView.append(' World');
      expect(textView.getText()).toBe('Hello World');
    });

    test('should have empty text by default', () => {
      expect(textView.getText()).toBe('');
    });
  });

  describe('Text Styling', () => {
    test('should set and get text size', () => {
      textView.setTextSize(24);
      expect(textView.getTextSize()).toBe(24);
    });

    test('should have default text size', () => {
      expect(textView.getTextSize()).toBe(16);
    });

    test('should set and get text color', () => {
      textView.setTextColor('#FF0000');
      expect(textView.getTextColor()).toBe('#FF0000');
    });

    test('should have default black color', () => {
      expect(textView.getTextColor()).toBe('#000000');
    });
  });

  describe('Dimensions', () => {
    test('should set width', () => {
      textView.setWidth('100%');
      expect(textView.toHarmonyConfig().width).toBe('100%');
    });

    test('should set height', () => {
      textView.setHeight(50);
      expect(textView.toHarmonyConfig().height).toBe(50);
    });

    test('should have wrap_content by default', () => {
      const config = textView.toHarmonyConfig();
      expect(config.width).toBe('wrap_content');
      expect(config.height).toBe('wrap_content');
    });
  });

  describe('Click Handling', () => {
    test('should set click listener', () => {
      const listener = jest.fn();
      textView.setOnClickListener(listener);
      textView.performClick();
      expect(listener).toHaveBeenCalled();
    });

    test('should not throw without listener', () => {
      expect(() => textView.performClick()).not.toThrow();
    });
  });

  describe('Configuration Export', () => {
    test('should export to HarmonyOS config', () => {
      textView.setText('Test');
      textView.setTextSize(20);
      textView.setTextColor('#00FF00');
      
      const config = textView.toHarmonyConfig();
      
      expect(config.text).toBe('Test');
      expect(config.textSize).toBe(20);
      expect(config.textColor).toBe('#00FF00');
    });

    test('should create HarmonyOS Text component', () => {
      textView.setText('Component');
      const component = textView.createHarmonyText();
      
      expect(component).toEqual({
        text: 'Component',
        textSize: 16,
        textColor: '#000000',
        width: 'wrap_content',
        height: 'wrap_content'
      });
    });
  });

  describe('Constructor Configuration', () => {
    test('should accept initial config', () => {
      const textView = new TextViewAdapter({
        text: 'Initial',
        textSize: 20,
        textColor: '#FF0000'
      });
      
      expect(textView.getText()).toBe('Initial');
      expect(textView.getTextSize()).toBe(20);
      expect(textView.getTextColor()).toBe('#FF0000');
    });
  });
});

// Test Summary
console.log(`
TextViewAdapter Test Suite
==========================
Total Tests: 20+
Coverage: Text, Styling, Dimensions, Click, Config
Status: Ready for execution
`);
